CREATE TABLE [dbo].[Book](
	[Id] [INT] IDENTITY(1000,1) NOT NULL,
	[Title] [NVARCHAR](300) NOT NULL,
	[Author] [NVARCHAR](200) NOT NULL,
	[Classification] [VARCHAR](20) NOT NULL,
	[Genre] [VARCHAR](20) NOT NULL,
	[Description] [NVARCHAR](MAX) NOT NULL,
 CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


